name: Token Pipeline and Pull Request

on:
  push:
    branches:
      - main

jobs:
  build_tokens_and_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Token Transformer
        run: node build-tokens.cjs

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          pr_title: 'Design Tokens Update'
          pr_body: '🎨 Design tokens were updated. This PR was created to update the code.'
          github_token: ${{ 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 }} # Replace with your GitHub personal access token
