name: Automate Design Tokens

on:
  push:
    branches:
      - main

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Change to Repository Root Directory
        run: cd $GITHUB_WORKSPACE

      - name: Print Working Directory
        run: pwd

      - name: Show package.json and npm install output
        run: |
          cat package.json
          npm install

      - name: List Installed Dependencies
        run: npm list

      - name: Run build-tokens.cjs
        run: node build-tokens.cjs
