name: Token Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Token Transformer
        run: node build-tokens.cjs

      - name: Commit files
        run: |
          git config --local user.email "jirayoos.pat@factsblend.com"
          git config --local user.name "GioFactblends"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}

