name: Process Figma Tokens PR

on: pull_request

jobs:
  run_if: # only if base branch is "figma-tokens"
    if: ${{ github.head_ref == 'main' }}
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # checkout to the head of this PR
      - uses: actions/checkout@master
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: npm install

      - name: Run token-transformer
        run: node build-tokens.cjs  

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GioFactblends
          author_email: jirayoos.pat@factsblend.com
          message: 'chore: style-dictionary output'
          add: '.'