name: Token Pipeline

on:
  push:
    branches:
      - main

jobs:
  copy_tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy CSS Tokens
        run: cp build/css/* build/

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit CSS Tokens
        run: |
          git add build/
          git commit -m "Copy CSS tokens"
          git push
